# Client Configuration
client.retry.attempts=3
client.retry.timeout.milliseconds=10000
client.quotes.service.earliest.date=2011-12-03T10:15:30Z
client.data.update.cron.expression=0 6 * * *
# Bundesbank url to get exchanging rates
#----------------------------------------------------
# Interpretation of the key BBEX3.M.AUD.EUR.BB.AC.A01
# Frequency (BBk)                               - M   - Monthly
# Area (ISO currency codes, list of currencies) - AUD - Australian dollar
# Currency denominator                          - EUR - Euro
# Content of time series                        - BB  - ECB euro reference exchange rates
# Rate type                                     - AC  - Middle
# Suffix                                        - A01 - End of month
# for more information see: https://www.bundesbank.de/dynamic/action/en/statistics/time-series-databases/help-for-sdmx-web-service/web-service-interface-data/855914/web-service-interface-data
#----------------------------------------------------
client.quotes.service.url=https://api.statistiken.bundesbank.de/rest/data
client.quotes.service.data.endpoint=/BBEX3/D..EUR.BB.AC.000

# Server Error Stack Trace Configuration
server.error.include-stacktrace=never

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
